logging:
  level:
    root: warn
    com.rest.api: info
  path: /home/songjackson96/app/log
  file:
    max-history: 7

spring:
  profiles: alpha
  datasource:
    url: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: update
      format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://board-api.greeners.shop
  redis:
    host: localhost
    port: 6379